// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Secrets_Sharing_BE;

#nullable disable

namespace Secrets_Sharing_BE.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230516142038_adduser")]
    partial class adduser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Secrets_Sharing_BE.Models.FileData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoDelete")
                        .HasColumnType("bit");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Protect")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UploadBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Protect");

                    b.HasIndex("UploadBy");

                    b.ToTable("FileData", (string)null);
                });

            modelBuilder.Entity("Secrets_Sharing_BE.Models.TextData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Protect")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UploadBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Protect");

                    b.HasIndex("UploadBy");

                    b.ToTable("TextData", (string)null);
                });

            modelBuilder.Entity("Secrets_Sharing_BE.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Secrets_Sharing_BE.Models.FileData", b =>
                {
                    b.HasOne("Secrets_Sharing_BE.Models.User", "User")
                        .WithMany("FileDatas")
                        .HasForeignKey("UploadBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Secrets_Sharing_BE.Models.TextData", b =>
                {
                    b.HasOne("Secrets_Sharing_BE.Models.User", "User")
                        .WithMany("TextDatas")
                        .HasForeignKey("UploadBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Secrets_Sharing_BE.Models.User", b =>
                {
                    b.Navigation("FileDatas");

                    b.Navigation("TextDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
