// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Secrets_Sharing_BE;

#nullable disable

namespace Secrets_Sharing_BE.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230512175059_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Secrets_Sharing_BE.Models.FileData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoDelete")
                        .HasColumnType("bit");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Protect")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UploadBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Protect");

                    b.ToTable("FileData", (string)null);
                });

            modelBuilder.Entity("Secrets_Sharing_BE.Models.TextData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Protect")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UploadBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Protect");

                    b.ToTable("TextData", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
